- name: add system user
  user:
    name: "{{ username }}"
    
- name: add to sudoers
  copy:
    content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/{{ username }}
  when: sudo
