---
- name: install repos
  dnf:
    name: "{{ repos_to_install | join(', ') }}"
    state: present
    disable_gpg_check: yes

- name: install packages
  dnf:
    name: "{{ packages_to_install | join(', ') }}"
    state: latest
